# Orders Data Analysis

In [20]:
# Import libraries
import zipfile
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("error")

In [10]:
import os
print(os.listdir())

['-1.14-windows.xml', '.anaconda', '.azuredatastudio', '.bash_history', '.cache', '.cline', '.conda', '.continuum', '.copilot', '.gitconfig', '.idlerc', '.ipynb_checkpoints', '.ipython', '.jupyter', '.kaggle', '.kivy', '.matplotlib', '.micromamba', '.ms-ad', '.ollama', '.spyder-py3', '.th-client', '.thumbnails', '.vscode', '1 Pandas1.ipynb', '1 Stats.ipynb', '10mar25_inferential_stat.ipynb', '2 Programs on conditions and Loops.ipynb', '26-02-25.ipynb', '3D Objects', 'age.c', 'Amazon-Products.csv', 'Amazon_Books.csv', 'anaconda_projects', 'AppData', 'Application Data', 'assignment condition-1.docx', 'assignment_condition1.ipynb', 'Banking.csv', 'Bank_loan.ipynb', 'Blinkit.ipynb', 'blinkit_data.csv', 'Bnking_case.ipynb', 'column_datatype.csv', 'Contacts', 'Cookies', 'customer', 'CUSTOMER SUPPORT DATA ANALYSIS & TICKET RESOLUTION.ipynb', 'customer_shopping_behavior (1).csv', 'customer_shopping_behavior.csv', 'customer_support_tickets.csv', 'data', 'data.csv', 'dataco-supplychaindata.csv', 'DatacosupplychainData.csv', 'Datatype_python_session1.ipynb', 'Desktop', 'dict_tupple_set_18-2,25.py.ipynb', 'dipidb', 'Diwali Sales Data.csv', 'diwali_data_project.ipynb', 'Documents', 'Downloads', 'EasyVisa.csv', 'EDA_sos1.ipynb', 'edurekha_assignment.py', 'employee.db', 'Eval_roundsession6_python.ipynb', 'eval_round_session6_python.ipynb', 'exceptional_cond_python_session9.ipnyb', 'Exploratory Data analysis.ipynb', 'Favorites', 'file.csv', 'filtered_comments.csv', 'financial_loan.xlsx', 'first-react-app', 'freq_table', 'function_session10_python.ipynb', 'function_session11_python.ipynb', 'function_session12_python.ipynb', 'function_session13_python.ipynb', 'function_session9_python.ipynb', 'HackerRank on Basics (1).ipynb', 'HackerRank on Basics (2).ipynb', 'HackerRank on Basics (3).ipynb', 'HackerRank on Basics (4).ipynb', 'HackerRank on Basics.ipynb', 'Healthcare.ipynb', 'hello.ipynb', 'If-else_session8_python.ipynb', 'IntelGraphicsProfiles', 'Inventory.db', 'Links', 'list_comprehension_session24.ipynb', 'list_session21.ipynb', 'list_session22.ipynb', 'Local Settings', 'logs', 'loops_session15_ipynb.ipynb', 'loops_session17.ipynb', 'loop_session14_python.ipynb', 'loop_session16.ipynb', 'loop_session17.ipynb', 'messy_employees.csv', 'messy_employee_sales.csv', 'Music', 'My Documents', 'Myntra dataset.ipynb', 'Myntra dataset.xlsx', 'Nested Loops  (2).ipynb', 'nested_cond_python_session8.ipnyb', 'Netflix_Dataset.csv', 'netflix_data_project.ipynb', 'netflix_project.ipynb', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.0.regtrans-ms', 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.1.regtrans-ms', 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.2.regtrans-ms', 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.blf', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'numerical_column_analysis.ipynb', 'numpy (1).ipynb', 'Numpy Exercises and Sol.ipynb', 'numpy.ipynb', 'OneDrive', 'output.csv', 'p1.htnl', 'Pandas100.ipynb', 'Pictures', 'practice.ipynb', 'practice_19mar.py.ipynb', 'practice_9apr.py.ipynb', 'PrintHood', 'PycharmProjects', 'python', 'python assignment-1(class room questions) (1).docx (1).pdf', 'python assignment-1(class room questions) (1).ipynb', 'python assignment-1(class room questions) .ipynb.pdf', 'python_assignment1.ipynb', 'Python_Assignment_Basics (1).ipynb', 'python_session5_print_statements.ipynb', 'python_session5_print_statements.py', 'python_session6_eval_round.ipynb', 'python_session6_eval_round.py', 'python_session_7_packages.ipny', 'Recent', 'Regional Sales Dataset.xlsx', 'Regional Sales project.ipynb', 'sales.db', 'Saved Games', 'Searches', 'SendTo', 'sentimentdataset.csv', 'sentiment_analysis_results.csv', 'sentiment_analysis_results.xlsx', 'Start Menu', 'statics_7march.ipynb', 'string_boolean_py.ipynb', 'string_session18.ipynb', 'string_session19.ipynb', 'string_session20.ipynb', 'swiggy_data.xlsx', 'Telco Customer Churn.csv', 'Telco-Customer-Churn.csv', 'tele customer churn.csv', 'Tele_customer_churn.ipynb', 'Templates', 'ticket_analysis_results.xlsx', 'ticket_analysis_summary.txt', 'tictac.py.ipynb', 'Typecasting_python_session4.ipynb', 'Uber-Jan-Feb-FOIL.csv', 'Untitled Folder', 'Untitled Folder 1', 'Untitled Folder 2', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled10.ipynb', 'Untitled100.ipynb', 'Untitled101.ipynb', 'Untitled102.ipynb', 'Untitled103.ipynb', 'Untitled104.ipynb', 'Untitled105.ipynb', 'Untitled106.ipynb', 'Untitled107.ipynb', 'Untitled108.ipynb', 'Untitled109.ipynb', 'Untitled11.ipynb', 'Untitled110.ipynb', 'Untitled111.ipynb', 'Untitled112.ipynb', 'Untitled113.ipynb', 'Untitled114.ipynb', 'Untitled115.ipynb', 'Untitled116.ipynb', 'Untitled117.ipynb', 'Untitled118.ipynb', 'Untitled119.ipynb', 'Untitled12.ipynb', 'Untitled120.ipynb', 'Untitled121.ipynb', 'Untitled122.ipynb', 'Untitled123.ipynb', 'Untitled124.ipynb', 'Untitled125.ipynb', 'Untitled126.ipynb', 'Untitled127.ipynb', 'Untitled128.ipynb', 'Untitled129.ipynb', 'Untitled13.ipynb', 'Untitled130.ipynb', 'Untitled131.ipynb', 'Untitled132.ipynb', 'Untitled133.ipynb', 'Untitled134.ipynb', 'Untitled135.ipynb', 'Untitled136.ipynb', 'Untitled137.ipynb', 'Untitled14.ipynb', 'Untitled15.ipynb', 'Untitled16.ipynb', 'Untitled17.ipynb', 'Untitled18.ipynb', 'Untitled19.ipynb', 'Untitled2.ipynb', 'Untitled20.ipynb', 'Untitled21.ipynb', 'Untitled22.ipynb', 'Untitled23.ipynb', 'Untitled24.ipynb', 'Untitled25.ipynb', 'Untitled26.ipynb', 'Untitled27.ipynb', 'Untitled28.ipynb', 'Untitled29.ipynb', 'Untitled3.ipynb', 'Untitled30.ipynb', 'Untitled31.ipynb', 'Untitled32.ipynb', 'Untitled33.ipynb', 'Untitled34.ipynb', 'Untitled35.ipynb', 'Untitled36.ipynb', 'Untitled37.ipynb', 'Untitled38.ipynb', 'Untitled39.ipynb', 'Untitled4.ipynb', 'Untitled40.ipynb', 'Untitled41.ipynb', 'Untitled42.ipynb', 'Untitled43.ipynb', 'Untitled44.ipynb', 'Untitled45.ipynb', 'Untitled46.ipynb', 'Untitled47.ipynb', 'Untitled48.ipynb', 'Untitled49.ipynb', 'Untitled5.ipynb', 'Untitled50-Copy1.ipynb', 'Untitled50.ipynb', 'Untitled51.ipynb', 'Untitled52.ipynb', 'Untitled53.ipynb', 'Untitled54.ipynb', 'Untitled55.ipynb', 'Untitled56.ipynb', 'Untitled57.ipynb', 'Untitled58.ipynb', 'Untitled59.ipynb', 'Untitled6.ipynb', 'Untitled60.ipynb', 'Untitled61.ipynb', 'Untitled62.ipynb', 'Untitled63.ipynb', 'Untitled64.ipynb', 'Untitled65.ipynb', 'Untitled66.ipynb', 'Untitled67.ipynb', 'Untitled68.ipynb', 'Untitled69.ipynb', 'Untitled7.ipynb', 'Untitled70.ipynb', 'Untitled71.ipynb', 'Untitled72.ipynb', 'Untitled73.ipynb', 'Untitled74.ipynb', 'Untitled75.ipynb', 'Untitled76.ipynb', 'Untitled77.ipynb', 'Untitled78.ipynb', 'Untitled79.ipynb', 'Untitled8.ipynb', 'Untitled80.ipynb', 'Untitled81.ipynb', 'Untitled82.ipynb', 'Untitled83.ipynb', 'Untitled84.ipynb', 'Untitled85.ipynb', 'Untitled86.ipynb', 'Untitled87.ipynb', 'Untitled88.ipynb', 'Untitled89.ipynb', 'Untitled9.ipynb', 'Untitled90.ipynb', 'Untitled91.ipynb', 'Untitled92.ipynb', 'Untitled93.ipynb', 'Untitled94.ipynb', 'Untitled95.ipynb', 'Untitled96.ipynb', 'Untitled97.ipynb', 'Untitled98.ipynb', 'Untitled99.ipynb', 'US_VISA_PREDICTION.ipynb', 'Variable_session1_python.ipynb', 'vediogame.ipynb', 'Videos', 'Visadataset.csv', 'WebstormProjects', 'world_population.csv', 'world_population.ipynb']

In [16]:
with zipfile.ZipFile(r'C:\Users\Sarita Bhuyan\Downloads\archive (25).zip') as zip_ref:
    zip_ref.extractall()

In [19]:
df = pd.read_csv('orders.csv')
df

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [22]:
df.duplicated()

np.int64(0)

In [24]:
df.nunique()

Order Id            9994
Order Date           730
Ship Mode              6
Segment                3
Country                1
City                 531
State                 49
Postal Code          631
Region                 4
Category               3
Sub Category          17
Product Id          1862
cost price           280
List Price           289
Quantity              14
Discount Percent       4
dtype: int64

In [26]:
df.describe()

,Order Id,Postal Code,cost price,List Price,Quantity,Discount Percent
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,201.189714,229.756854,3.789574,3.484090
std,2885.163629,32063.693350,537.743203,623.245839,2.225110,1.114211
min,1.000000,1040.000000,0.000000,0.000000,1.000000,2.000000
25%,2499.250000,23223.000000,20.000000,20.000000,2.000000,2.000000
50%,4997.500000,56430.500000,50.000000,50.000000,3.000000,3.000000
75%,7495.750000,90008.000000,180.000000,210.000000,5.000000,4.000000
max,9994.000000,99301.000000,18110.000000,22640.000000,14.000000,5.000000

In [28]:
df.isnull().sum()

Order Id            0
Order Date          0
Ship Mode           1
Segment             0
Country             0
City                0
State               0
Postal Code         0
Region              0
Category            0
Sub Category        0
Product Id          0
cost price          0
List Price          0
Quantity            0
Discount Percent    0
dtype: int64

In [29]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', 'Not Available', 'unknown',
       'First Class', nan, 'Same Day'], dtype=object)

In [36]:
df['Ship Mode'] = df['Ship Mode'].replace(['Not Available', 'unknown'], np.nan)

In [37]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [39]:
df.columns

Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',
       'Product Id', 'cost price', 'List Price', 'Quantity',
       'Discount Percent'],
      dtype='object')

In [42]:
df.rename(columns={
    'Order Id': 'order_id',
    'Ship Mode': 'ship_mode'
}, inplace=True)
df

,order_id,Order Date,ship_mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [43]:
df.columns=df.columns.str.lower()

In [44]:
df.columns=df.columns.str.replace(' ','__')

In [45]:
df.head(5)

,order_id,order__date,ship_mode,segment,country,city,state,postal__code,region,category,sub__category,product__id,cost__price,list__price,quantity,discount__percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [56]:
df['discount']=df['list__price'] * df['discount__percent'] * .01
df

,order_id,order__date,ship_mode,segment,country,city,state,postal__code,region,category,sub__category,product__id,cost__price,list__price,quantity,discount__percent,discount
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2

In [59]:
df['sale_price'] = df['list__price'] - df['discount']
df

,order_id,order__date,ship_mode,segment,country,city,state,postal__code,region,category,sub__category,product__id,cost__price,list__price,quantity,discount__percent,discount,sale_price
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8

In [62]:
df['profit'] = df['sale_price'] - df['cost__price']
df

,order_id,order__date,ship_mode,segment,country,city,state,postal__code,region,category,sub__category,product__id,cost__price,list__price,quantity,discount__percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [66]:
df['order__date'] = pd.to_datetime(df['order__date'],format="%Y-%m-%d")
df

,order_id,order__date,ship_mode,segment,country,city,state,postal__code,region,category,sub__category,product__id,cost__price,list__price,quantity,discount__percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [76]:
df.drop(columns=['list_price','cost_price','discount_percent'], inplace=True, errors='ignore')
df

,order_id,order__date,ship_mode,segment,country,city,state,postal__code,region,category,sub__category,product__id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [95]:
import mysql.connector
conn = mysql.connector.connect(
    host="127.0.0.1",
    user="root",
    password="1234",
    database="orders"
)

from sqlalchemy import create_engine
engine = create_engine("mysql+mysqlconnector://root:1234@127.0.0.1/orders")
df.to_sql('orders', con=engine, if_exists='append', index=False)
cursor = conn.cursor()
cursor.execute("SELECT * FROM orders")

for row in cursor.fetchall():
    print(row)

(1, datetime.date(2023, 3, 1), 'Second Class', 'Consumer', 'United States', 'Henderson', 'Kentucky', '42420', 'South', 'Furniture', 'Bookcases', 'FUR-BO-10001798', 2, Decimal('5.20'), Decimal('254.80'), Decimal('14.80'))
(2, datetime.date(2023, 8, 15), 'Second Class', 'Consumer', 'United States', 'Henderson', 'Kentucky', '42420', 'South', 'Furniture', 'Chairs', 'FUR-CH-10000454', 3, Decimal('21.90'), Decimal('708.10'), Decimal('108.10'))
(3, datetime.date(2023, 1, 10), 'Second Class', 'Corporate', 'United States', 'Los Angeles', 'California', '90036', 'West', 'Office Supplies', 'Labels', 'OFF-LA-10000240', 2, Decimal('0.50'), Decimal('9.50'), Decimal('-0.50'))
(4, datetime.date(2022, 6, 18), 'Standard Class', 'Consumer', 'United States', 'Fort Lauderdale', 'Florida', '33311', 'South', 'Furniture', 'Tables', 'FUR-TA-10000577', 5, Decimal('19.20'), Decimal('940.80'), Decimal('160.80'))
(5, datetime.date(2022, 7, 13), 'Standard Class', 'Consumer', 'United States', 'Fort Lauderdale', 'Florida', '33311', 'South', 'Office Supplies', 'Storage', 'OFF-ST-10000760', 2, Decimal('1.00'), Decimal('19.00'), Decimal('-1.00'))
(6, datetime.date(2022, 3, 13), None, 'Consumer', 'United States', 'Los Angeles', 'California', '90032', 'West', 'Furniture', 'Furnishings', 'FUR-FU-10001487', 7, Decimal('1.50'), Decimal('48.50'), Decimal('-1.50'))
(7, datetime.date(2022, 12, 28), 'Standard Class', 'Consumer', 'United States', 'Los Angeles', 'California', '90032', 'West', 'Office Supplies', 'Art', 'OFF-AR-10002833', 4, Decimal('0.30'), Decimal('9.70'), Decimal('-0.30'))
(8, datetime.date(2022, 1, 25), 'Standard Class', 'Consumer', 'United States', 'Los Angeles', 'California', '90032', 'West', 'Technology', 'Phones', 'TEC-PH-10002275', 6, Decimal('45.50'), Decimal('864.50'), Decimal('4.50'))
(9, datetime.date(2023, 3, 23), None, 'Consumer', 'United States', 'Los Angeles', 'California', '90032', 'West', 'Office Supplies', 'Binders', 'OFF-BI-10003910', 3, Decimal('0.40'), Decimal('19.60'), Decimal('-0.40'))
(10, datetime.date(2023, 5, 16), 'Standard Class', 'Consumer', 'United States', 'Los Angeles', 'California', '90032', 'West', 'Office Supplies', 'Appliances', 'OFF-AP-10002892', 5, Decimal('3.30'), Decimal('106.70'), Decimal('16.70'))
(11, datetime.date(2023, 3, 31), None, 'Consumer', 'United States', 'Los Angeles', 'California', '90032', 'West', 'Furniture', 'Tables', 'FUR-TA-10001539', 9, Decimal('51.30'), Decimal('1658.70'), Decimal('188.70'))
(12, datetime.date(2023, 12, 25), None, 'Consumer', 'United States', 'Los Angeles', 'California', '90032', 'West', 'Technology', 'Phones', 'TEC-PH-10002033', 4, Decimal('27.30'), Decimal('882.70'), Decimal('132.70'))
(13, datetime.date(2022, 2, 11), 'Standard Class', 'Consumer', 'United States', 'Concord', 'North Carolina', '28027', 'South', 'Office Supplies', 'Paper', 'OFF-PA-10002365', 3, Decimal('0.60'), Decimal('19.40'), Decimal('-0.60'))
(14, datetime.date(2023, 7, 18), 'Standard Class', 'Consumer', 'United States', 'Seattle', 'Washington', '98103', 'West', 'Office Supplies', 'Binders', 'OFF-BI-10003656', 3, Decimal('8.20'), Decimal('401.80'), Decimal('41.80'))
(15, datetime.date(2023, 11, 9), None, 'Home Office', 'United States', 'Fort Worth', 'Texas', '76106', 'Central', 'Office Supplies', 'Appliances', 'OFF-AP-10002311', 5, Decimal('3.50'), Decimal('66.50'), Decimal('6.50'))
(16, datetime.date(2022, 6, 18), 'Standard Class', 'Home Office', 'United States', 'Fort Worth', 'Texas', '76106', 'Central', 'Office Supplies', 'Binders', 'OFF-BI-10000756', 3, Decimal('0.00'), Decimal('0.00'), Decimal('0.00'))
(17, datetime.date(2022, 2, 4), 'Standard Class', 'Consumer', 'United States', 'Madison', 'Wisconsin', '53711', 'Central', 'Office Supplies', 'Storage', 'OFF-ST-10004186', 6, Decimal('20.10'), Decimal('649.90'), Decimal('39.90'))
(18, datetime.date(2023, 8, 4), 'Second Class', 'Consumer', 'United States', 'West Jordan', 'Utah', '84084', 'West', 'Office Supplies', 'Storage', 'OFF-ST-10000107', 2, Decimal('2.40'), Decimal('57.60'), Decimal('-2.40'))
(19, datetime.date(2022, 1, 23), 'Second Class', 'Consumer', 'United States', 'San Francisco', 'California', '94109', 'West', 'Office Supplies', 'Art', 'OFF-AR-10003056', 2, Decimal('0.40'), Decimal('9.60'), Decimal('-0.40'))
(20, datetime.date(2022, 1, 11), 'Second Class', 'Consumer', 'United States', 'San Francisco', 'California', '94109', 'West', 'Technology', 'Phones', 'TEC-PH-10001949', 3, Decimal('6.30'), Decimal('203.70'), Decimal('33.70'))
(21, datetime.date(2022, 10, 5), 'Second Class', 'Consumer', 'United States', 'San Francisco', 'California', '94109', 'West', 'Office Supplies', 'Binders', 'OFF-BI-10002215', 4, Decimal('0.40'), Decimal('19.60'), Decimal('-0.40'))
(22, datetime.date(2023, 7, 16), 'Standard Class', 'Corporate', 'United States', 'Fremont', 'Nebraska', '68025', 'Central', 'Office Supplies', 'Art', 'OFF-AR-10000246', 7, Decimal('0.80'), Decimal('19.20'), Decimal('-0.80'))
(23, datetime.date(2023, 5, 6), 'Standard Class', 'Corporate', 'United States', 'Fremont', 'Nebraska', '68025', 'Central', 'Office Supplies', 'Appliances', 'OFF-AP-10001492', 7, Decimal('1.80'), Decimal('58.20'), Decimal('8.20'))
(24, datetime.date(2023, 5, 21), 'Second Class', 'Consumer', 'United States', 'Philadelphia', 'Pennsylvania', '19140', 'East', 'Furniture', 'Chairs', 'FUR-CH-10002774', 2, Decimal('2.80'), Decimal('67.20'), Decimal('7.20'))
(25, datetime.date(2023, 2, 24), 'Standard Class', 'Consumer', 'United States', 'Orem', 'Utah', '84057', 'West', 'Furniture', 'Tables', 'FUR-TA-10000577', 3, Decimal('52.00'), Decimal('988.00'), Decimal('88.00'))
(26, datetime.date(2022, 6, 20), 'Second Class', 'Consumer', 'United States', 'Los Angeles', 'California', '90049', 'West', 'Office Supplies', 'Binders', 'OFF-BI-10001634', 2, Decimal('0.50'), Decimal('9.50'), Decimal('-0.50'))
(27, datetime.date(2022, 2, 8), 'Second Class', 'Consumer', 'United States', 'Los Angeles', 'California', '90049', 'West', 'Technology', 'Accessories', 'TEC-AC-10003027', 3, Decimal('2.70'), Decimal('87.30'), Decimal('7.30'))
(28, datetime.date(2023, 12, 11), 'Standard Class', 'Consumer', 'United States', 'Philadelphia', 'Pennsylvania', '19140', 'East', 'Furniture', 'Bookcases', 'FUR-BO-10004834', 7, Decimal('92.40'), Decimal('2987.60'), Decimal('247.60'))
(29, datetime.date(2022, 8, 21), 'Standard Class', 'Consumer', 'United States', 'Philadelphia', 'Pennsylvania', '19140', 'East', 'Office Supplies', 'Binders', 'OFF-BI-10000474', 2, Decimal('0.50'), Decimal('9.50'), Decimal('-0.50'))
(30, datetime.date(2022, 8, 14), 'Standard Class', 'Consumer', 'United States', 'Philadelphia', 'Pennsylvania', '19140', 'East', 'Furniture', 'Furnishings', 'FUR-FU-10004848', 3, Decimal('4.80'), Decimal('115.20'), Decimal('15.20'))
(31, datetime.date(2022, 11, 20), 'Standard Class', 'Consumer', 'United States', 'Philadelphia', 'Pennsylvania', '19140', 'East', 'Office Supplies', 'Envelopes', 'OFF-EN-10001509', 2, Decimal('0.00'), Decimal('0.00'), Decimal('0.00'))
(32, datetime.date(2023, 1, 19), 'Standard Class', 'Consumer', 'United States', 'Philadelphia', 'Pennsylvania', '19140', 'East', 'Office Supplies', 'Art', 'OFF-AR-10004042', 6, Decimal('3.60'), Decimal('86.40'), Decimal('16.40'))
(33, datetime.date(2023, 1, 30), 'Standard Class', 'Consumer', 'United States', 'Philadelphia', 'Pennsylvania', '19140', 'East', 'Office Supplies', 'Binders', 'OFF-BI-10001525', 6, Decimal('0.50'), Decimal('9.50'), Decimal('-0.50'))
(34, datetime.date(2022, 6, 3), 'Standard Class', 'Consumer', 'United States', 'Philadelphia', 'Pennsylvania', '19140', 'East', 'Office Supplies', 'Art', 'OFF-AR-10001683', 2, Decimal('0.80'), Decimal('19.20'), Decimal('-0.80'))
(35, datetime.date(2022, 9, 28), 'Second Class', 'Home Office', 'United States', 'Houston', 'Texas', '77095', 'Central', 'Office Supplies', 'Paper', 'OFF-PA-10000249', 3, Decimal('0.90'), Decimal('29.10'), Decimal('-0.90'))
(36, datetime.date(2022, 10, 30), 'First Class', 'Corporate', 'United States', 'Richardson', 'Texas', '75080', 'Central', 'Technology', 'Phones', 'TEC-PH-10004977', 7, Decimal('55.00'), Decimal('1045.00'), Decimal('25.00'))
(37, datetime.date(2023, 7, 27), 'First Class', 'Corporate', 'United States', 'Richardson', 'Texas', '75080', 'Central', 'Furniture', 'Furnishings', 'FUR-FU-10003664', 5, Decimal('7.60'), Decimal('182.40'), Decimal('2.40'))
(38, datetime.date(2023, 3, 7), 'Standard Class', 'Home Office', 'United States', 'Houston', 'Texas', '77041', 'Central', 'Office Supplies', 'Envelopes', 'OFF-EN-10002986', 9, Decimal('2.20'), Decimal('107.80'), Decimal('17.80'))
(39, datetime.date(2023, 8, 18), 'Standard Class', 'Home Office', 'United States', 'Houston', 'Texas', '77041', 'Central', 'Furniture', 'Bookcases', 'FUR-BO-10002545', 3, Decimal('10.60'), Decimal('519.40'), Decimal('59.40'))
(40, datetime.date(2022, 1, 20), 'Standard Class', 'Home Office', 'United States', 'Houston', 'Texas', '77041', 'Central', 'Furniture', 'Chairs', 'FUR-CH-10004218', 3, Decimal('4.20'), Decimal('205.80'), Decimal('5.80'))
(41, datetime.date(2023, 6, 29), 'Standard Class', 'Home Office', 'United States', 'Houston', 'Texas', '77041', 'Central', 'Technology', 'Phones', 'TEC-PH-10000486', 4, Decimal('18.50'), Decimal('351.50'), Decimal('1.50'))
(42, datetime.date(2022, 6, 28), 'Standard Class', 'Corporate', 'United States', 'Naperville', 'Illinois', '60540', 'Central', 'Technology', 'Phones', 'TEC-PH-10004093', 4, Decimal('4.50'), Decimal('145.50'), Decimal('5.50'))
(43, datetime.date(2023, 2, 9), 'Standard Class', 'Corporate', 'United States', 'Los Angeles', 'California', '90049', 'West', 'Office Supplies', 'Storage', 'OFF-ST-10003479', 2, Decimal('4.00'), Decimal('76.00'), Decimal('6.00'))
(44, datetime.date(2023, 9, 18), 'Standard Class', 'Corporate', 'United States', 'Melbourne', 'Florida', '32935', 'South', 'Office Supplies', 'Storage', 'OFF-ST-10003282', 2, Decimal('4.00'), Decimal('96.00'), Decimal('6.00'))
(45, datetime.date(2022, 11, 11), 'First Class', 'Corporate', 'United States', 'Eagan', 'Minnesota', '55122', 'Central', 'Technology', 'Accessories', 'TEC-AC-10000171', 2, Decimal('1.00'), Decimal('49.00'), Decimal('9.00'))
(46, datetime.date(2022, 5, 27), 'First Class', 'Corporate', 'United States', 'Eagan', 'Minnesota', '55122', 'Central', 'Office Supplies', 'Binders', 'OFF-BI-10003291', 2, Decimal('1.00'), Decimal('19.00'), Decimal('-1.00'))
(47, datetime.date(2023, 2, 3), 'Second Class', 'Consumer', 'United States', 'Westland', 'Michigan', '48185', 'Central', 'Office Supplies', 'Storage', 'OFF-ST-10001713', 4, Decimal('8.40'), Decimal('201.60'), Decimal('21.60'))
(48, datetime.date(2022, 2, 16), 'Standard Class', 'Consumer', 'United States', 'Dover', 'Delaware', '19901', 'East', 'Technology', 'Accessories', 'TEC-AC-10002167', 3, Decimal('2.50'), Decimal('47.50'), Decimal('-2.50'))
(49, datetime.date(2022, 5, 6), 'Standard Class', 'Consumer', 'United States', 'Dover', 'Delaware', '19901', 'East', 'Technology', 'Phones', 'TEC-PH-10003988', 2, Decimal('0.80'), Decimal('19.20'), Decimal('-0.80'))
(50, datetime.date(2023, 6, 18), 'Standard Class', 'Consumer', 'United States', 'New Albany', 'Indiana', '47150', 'Central', 'Office Supplies', 'Binders', 'OFF-BI-10004410', 6, Decimal('1.60'), Decimal('38.40'), Decimal('8.40'))
(51, datetime.date(2022, 1, 11), 'Standard Class', 'Consumer', 'United States', 'New Albany', 'Indiana', '47150', 'Central', 'Office Supplies', 'Labels', 'OFF-LA-10002762', 6, Decimal('3.20'), Decimal('76.80'), Decimal('6.80'))
(52, datetime.date(2023, 9, 9), 'Standard Class', 'Consumer', 'United States', 'New Albany', 'Indiana', '47150', 'Central', 'Furniture', 'Furnishings', 'FUR-FU-10001706', 2, Decimal('0.40'), Decimal('9.60'), Decimal('-0.40'))
(53, datetime.date(2022, 1, 31), 'Standard Class', 'Consumer', 'United States', 'New Albany', 'Indiana', '47150', 'Central', 'Furniture', 'Chairs', 'FUR-CH-10003061', 1, Decimal('4.50'), Decimal('85.50'), Decimal('15.50'))
(54, datetime.date(2023, 7, 30), 'Standard Class', 'Corporate', 'United States', 'New York City', 'New York', '10024', 'East', 'Office Supplies', 'Fasteners', 'OFF-FA-10000304', 7, Decimal('0.60'), Decimal('19.40'), Decimal('-0.60'))
(55, datetime.date(2023, 10, 17), 'Standard Class', 'Corporate', 'United States', 'New York City', 'New York', '10024', 'East', 'Technology', 'Phones', 'TEC-PH-10002447', 5, Decimal('41.20'), Decimal('988.80'), Decimal('138.80'))
(56, datetime.date(2023, 7, 6), 'First Class', 'Consumer', 'United States', 'Troy', 'New York', '12180', 'East', 'Office Supplies', 'Storage', 'OFF-ST-10000604', 6, Decimal('10.50'), Decimal('199.50'), Decimal('-0.50'))
(57, datetime.date(2023, 9, 15), 'First Class', 'Consumer', 'United States', 'Troy', 'New York', '12180', 'East', 'Office Supplies', 'Paper', 'OFF-PA-10001569', 5, Decimal('1.50'), Decimal('28.50'), Decimal('-1.50'))
(58, datetime.date(2022, 8, 9), 'First Class', 'Consumer', 'United States', 'Troy', 'New York', '12180', 'East', 'Furniture', 'Chairs', 'FUR-CH-10003968', 5, Decimal('6.40'), Decimal('313.60'), Decimal('23.60'))
(59, datetime.date(2022, 4, 5), 'First Class', 'Consumer', 'United States', 'Troy', 'New York', '12180', 'East', 'Office Supplies', 'Paper', 'OFF-PA-10000587', 2, Decimal('0.40'), Decimal('9.60'), Decimal('-0.40'))
(60, datetime.date(2023, 6, 24), 'First Class', 'Consumer', 'United States', 'Troy', 'New York', '12180', 'East', 'Technology', 'Accessories', 'TEC-AC-10002167', 2, Decimal('1.50'), Decimal('28.50'), Decimal('8.50'))
(61, datetime.date(2022, 3, 10), 'First Class', 'Consumer', 'United States', 'Troy', 'New York', '12180', 'East', 'Office Supplies', 'Binders', 'OFF-BI-10001460', 4, Decimal('1.00'), Decimal('49.00'), Decimal('9.00'))
(62, datetime.date(2023, 4, 8), 'First Class', 'Consumer', 'United States', 'Troy', 'New York', '12180', 'East', 'Office Supplies', 'Art', 'OFF-AR-10001868', 1, Decimal('0.00'), Decimal('0.00'), Decimal('0.00'))
(63, datetime.date(2023, 10, 16), 'Standard Class', 'Consumer', 'United States', 'Los Angeles', 'California', '90004', 'West', 'Technology', 'Accessories', 'TEC-AC-10004633', 2, Decimal('0.30'), Decimal('9.70'), Decimal('-0.30'))
(64, datetime.date(2023, 8, 2), 'Standard Class', 'Consumer', 'United States', 'Los Angeles', 'California', '90004', 'West', 'Office Supplies', 'Binders', 'OFF-BI-10001078', 6, Decimal('0.60'), Decimal('29.40'), Decimal('9.40'))
(65, datetime.date(2022, 11, 5), 'Standard Class', 'Consumer', 'United States', 'Los Angeles', 'California', '90004', 'West', 'Office Supplies', 'Paper', 'OFF-PA-10003892', 3, Decimal('7.50'), Decimal('142.50'), Decimal('12.50'))
(66, datetime.date(2022, 5, 6), 'Standard Class', 'Consumer', 'United States', 'Los Angeles', 'California', '90004', 'West', 'Furniture', 'Furnishings', 'FUR-FU-10000397', 4, Decimal('1.60'), Decimal('78.40'), Decimal('8.40'))
(67, datetime.date(2022, 3, 26), 'Standard Class', 'Home Office', 'United States', 'Chicago', 'Illinois', '60610', 'Central', 'Furniture', 'Chairs', 'FUR-CH-10001146', 5, Decimal('10.50'), Decimal('199.50'), Decimal('19.50'))
(68, datetime.date(2022, 4, 10), 'Standard Class', 'Corporate', 'United States', 'Gilbert', 'Arizona', '85234', 'West', 'Office Supplies', 'Art', 'OFF-AR-10002671', 8, Decimal('33.30'), Decimal('1076.70'), Decimal('136.70'))
(69, datetime.date(2022, 8, 12), 'Standard Class', 'Corporate', 'United States', 'Gilbert', 'Arizona', '85234', 'West', 'Technology', 'Phones', 'TEC-PH-10002726', 4, Decimal('5.10'), Decimal('164.90'), Decimal('4.90'))
(70, datetime.date(2022, 2, 25), 'First Class', 'Consumer', 'United States', 'Springfield', 'Virginia', '22153', 'South', 'Office Supplies', 'Paper', 'OFF-PA-10000482', 2, Decimal('1.60'), Decimal('78.40'), Decimal('8.40'))
(71, datetime.date(2022, 11, 29), 'Standard Class', 'Consumer', 'United States', 'New York City', 'New York', '10009', 'East', 'Office Supplies', 'Binders', 'OFF-BI-10004654', 1, Decimal('0.00'), Decimal('0.00'), Decimal('0.00'))
(72, datetime.date(2022, 12, 18), 'Second Class', 'Consumer', 'United States', 'Jackson', 'Michigan', '49201', 'Central', 'Office Supplies', 'Paper', 'OFF-PA-10004675', 3, Decimal('0.60'), Decimal('19.40'), Decimal('-0.60'))
(73, datetime.date(2023, 3, 7), 'Standard Class', 'Consumer', 'United States', 'Memphis', 'Tennessee', '38109', 'South', 'Furniture', 'Chairs', 'FUR-CH-10000513', 8, Decimal('16.60'), Decimal('813.40'), Decimal('23.40'))
(74, datetime.date(2023, 7, 12), 'Standard Class', 'Consumer', 'United States', 'Memphis', 'Tennessee', '38109', 'South', 'Furniture', 'Furnishings', 'FUR-FU-10003708', 2, Decimal('3.00'), Decimal('97.00'), Decimal('7.00'))
(75, datetime.date(2022, 10, 21), 'Standard Class', 'Consumer', 'United States', 'Memphis', 'Tennessee', '38109', 'South', 'Office Supplies', 'Storage', 'OFF-ST-10004123', 1, Decimal('1.40'), Decimal('68.60'), Decimal('8.60'))
(76, datetime.date(2023, 4, 17), 'First Class', 'Corporate', 'United States', 'Houston', 'Texas', '77041', 'Central', 'Office Supplies', 'Binders', 'OFF-BI-10004182', 3, Decimal('0.00'), Decimal('0.00'), Decimal('0.00'))
(77, datetime.date(2023, 5, 20), 'First Class', 'Corporate', 'United States', 'Houston', 'Texas', '77041', 'Central', 'Furniture', 'Furnishings', 'FUR-FU-10000260', 3, Decimal('0.40'), Decimal('9.60'), Decimal('-0.40'))
(78, datetime.date(2023, 5, 13), 'First Class', 'Corporate', 'United States', 'Houston', 'Texas', '77041', 'Central', 'Office Supplies', 'Storage', 'OFF-ST-10000615', 3, Decimal('0.60'), Decimal('29.40'), Decimal('9.40'))
(79, datetime.date(2022, 10, 20), 'Second Class', 'Consumer', 'United States', 'Houston', 'Texas', '77070', 'Central', 'Furniture', 'Furnishings', 'FUR-FU-10003194', 5, Decimal('0.40'), Decimal('19.60'), Decimal('-0.40'))
(80, datetime.date(2023, 10, 22), 'First Class', 'Corporate', 'United States', 'Decatur', 'Alabama', '35601', 'South', 'Office Supplies', 'Appliances', 'OFF-AP-10002118', 1, Decimal('6.30'), Decimal('203.70'), Decimal('13.70'))
(81, datetime.date(2022, 7, 20), 'First Class', 'Corporate', 'United States', 'Decatur', 'Alabama', '35601', 'South', 'Office Supplies', 'Binders', 'OFF-BI-10002309', 3, Decimal('0.40'), Decimal('19.60'), Decimal('-0.40'))
(82, datetime.date(2022, 11, 16), 'Standard Class', 'Consumer', 'United States', 'San Francisco', 'California', '94122', 'West', 'Office Supplies', 'Art', 'OFF-AR-10002053', 5, Decimal('0.50'), Decimal('9.50'), Decimal('-0.50'))
(83, datetime.date(2022, 11, 10), 'Standard Class', 'Consumer', 'United States', 'San Francisco', 'California', '94122', 'West', 'Office Supplies', 'Storage', 'OFF-ST-10002370', 1, Decimal('0.80'), Decimal('19.20'), Decimal('-0.80'))
(84, datetime.date(2022, 3, 15), 'Standard Class', 'Corporate', 'United States', 'Durham', 'North Carolina', '27707', 'South', 'Office Supplies', 'Envelopes', 'OFF-EN-10000927', 7, Decimal('6.00'), Decimal('194.00'), Decimal('14.00'))
(85, datetime.date(2023, 10, 3), 'First Class', 'Home Office', 'United States', 'Chicago', 'Illinois', '60623', 'Central', 'Office Supplies', 'Storage', 'OFF-ST-10003656', 3, Decimal('4.60'), Decimal('225.40'), Decimal('15.40'))
(86, datetime.date(2022, 3, 20), 'Second Class', 'Consumer', 'United States', 'Columbia', 'South Carolina', '29203', 'South', 'Furniture', 'Chairs', 'FUR-CH-10000863', 2, Decimal('15.00'), Decimal('285.00'), Decimal('25.00'))
(87, datetime.date(2023, 12, 4), 'Standard Class', 'Consumer', 'United States', 'Rochester', 'Minnesota', '55901', 'Central', 'Technology', 'Accessories', 'TEC-AC-10001998', 1, Decimal('1.00'), Decimal('19.00'), Decimal('-1.00'))
(88, datetime.date(2023, 11, 24), 'Standard Class', 'Consumer', 'United States', 'Rochester', 'Minnesota', '55901', 'Central', 'Office Supplies', 'Labels', 'OFF-LA-10000134', 2, Decimal('0.50'), Decimal('9.50'), Decimal('-0.50'))

In [94]:
from sqlalchemy import create_engine

engine = create_engine("mysql+mysqlconnector://root:1234@127.0.0.1/orders")